- name: Update package cache and install a package
  hosts: all
  become_user: ken
  become: true
  tasks:
    - name: apt-get update
      ansible.builtin.apt:
        update_cache: yes
    - name: apt-get dist-upgrade
      ansible.builtin.apt:
        upgrade: dist
    - name: Remove dependencies that are no longer required
      ansible.builtin.apt:
        autoremove: true