- hosts: all
    
  tasks:
    - name: apt-get update
      ansible.builtin.apt:
        update_cache: yes
      become: true
    - name: apt-get dist-upgrade
      ansible.builtin.apt:
        upgrade: dist
      become: true
    - name: Remove dependencies that are no longer required
      ansible.builtin.apt:
        autoremove: true
      become: true